services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "${APP_VERSION:-0.6.6-alpha}"
        DEV_MODE: "${DEV_MODE:-false}"
    container_name: dosh
    restart: unless-stopped
    volumes:
      - dosh-data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/dosh.db}
      - TZ=${TZ:-Australia/Sydney}
    ports:
      - "3080:80"

volumes:
  dosh-data:
