services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        APP_VERSION: "0.6.4-alpha"
        DEV_MODE: "true"
    container_name: dosh-backend
    restart: unless-stopped
    volumes:
      - dosh-data:/app/data
    environment:
      - APP_VERSION=0.6.4-alpha
      - DEV_MODE=true
      - DATABASE_URL=sqlite:////app/data/dosh.db
      - TZ=Australia/Sydney
    ports:
      - "3080:80"

volumes:
  dosh-data:
