sonar.projectName=Dosh
sonar.sourceEncoding=UTF-8
sonar.organization=mixednutts

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src/__tests__

sonar.exclusions=frontend/src/__tests__/**
sonar.test.inclusions=backend/tests/**,frontend/src/__tests__/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
