"""baseline_current_schema

Revision ID: abfa823847b9
Revises: 
Create Date: 2026-04-08 07:21:55.102197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'abfa823847b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('budgetid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budgetowner', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('budget_frequency', sa.String(), nullable=False),
    sa.Column('variance_mode', sa.String(), nullable=False),
    sa.Column('auto_add_surplus_to_investment', sa.Boolean(), nullable=False),
    sa.Column('acceptable_expense_overrun_pct', sa.Integer(), nullable=False),
    sa.Column('comfortable_surplus_buffer_pct', sa.Integer(), nullable=False),
    sa.Column('maximum_deficit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revision_sensitivity', sa.Integer(), nullable=False),
    sa.Column('savings_priority', sa.Integer(), nullable=False),
    sa.Column('period_criticality_bias', sa.Integer(), nullable=False),
    sa.Column('allow_cycle_lock', sa.Boolean(), nullable=False),
    sa.Column('account_naming_preference', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('budgetid')
    )
    op.create_table('paytypes',
    sa.Column('paytype', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('paytype')
    )
    op.create_table('balancetypes',
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('balancedesc', sa.String(), nullable=False),
    sa.Column('balance_type', sa.String(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['budgetid'], ['budgets.budgetid'], ),
    sa.PrimaryKeyConstraint('budgetid', 'balancedesc')
    )
    op.create_table('expenseitems',
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('expensedesc', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('freqtype', sa.String(), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('paytype', sa.String(), nullable=True),
    sa.Column('revisionnum', sa.Integer(), nullable=False),
    sa.Column('effectivedate', sa.DateTime(), nullable=True),
    sa.Column('expenseamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budgetid'], ['budgets.budgetid'], ),
    sa.ForeignKeyConstraint(['paytype'], ['paytypes.paytype'], ),
    sa.PrimaryKeyConstraint('budgetid', 'expensedesc')
    )
    op.create_table('financialperiods',
    sa.Column('finperiodid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('startdate', sa.DateTime(), nullable=False),
    sa.Column('enddate', sa.DateTime(), nullable=False),
    sa.Column('budgetowner', sa.String(), nullable=True),
    sa.Column('islocked', sa.Boolean(), nullable=False),
    sa.Column('cycle_status', sa.String(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budgetid'], ['budgets.budgetid'], ),
    sa.PrimaryKeyConstraint('finperiodid')
    )
    op.create_table('incometypes',
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('incomedesc', sa.String(), nullable=False),
    sa.Column('issavings', sa.Boolean(), nullable=False),
    sa.Column('autoinclude', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('linked_account', sa.String(), nullable=True),
    sa.Column('revisionnum', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budgetid'], ['budgets.budgetid'], ),
    sa.PrimaryKeyConstraint('budgetid', 'incomedesc')
    )
    op.create_table('investmentitems',
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('investmentdesc', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effectivedate', sa.DateTime(), nullable=True),
    sa.Column('initial_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('linked_account_desc', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('revisionnum', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budgetid'], ['budgets.budgetid'], ),
    sa.PrimaryKeyConstraint('budgetid', 'investmentdesc')
    )
    op.create_table('setuprevisionevents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('item_desc', sa.String(), nullable=False),
    sa.Column('revisionnum', sa.Integer(), nullable=False),
    sa.Column('changed_fields_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budgetid'], ['budgets.budgetid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodbalances',
    sa.Column('finperiodid', sa.Integer(), nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('balancedesc', sa.String(), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closing_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('movement_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['budgetid', 'balancedesc'], ['balancetypes.budgetid', 'balancetypes.balancedesc'], ),
    sa.ForeignKeyConstraint(['finperiodid'], ['financialperiods.finperiodid'], ),
    sa.PrimaryKeyConstraint('finperiodid', 'balancedesc')
    )
    op.create_table('periodcloseouts',
    sa.Column('finperiodid', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('carry_forward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('health_snapshot_json', sa.Text(), nullable=False),
    sa.Column('totals_snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finperiodid'], ['financialperiods.finperiodid'], ),
    sa.PrimaryKeyConstraint('finperiodid')
    )
    op.create_table('periodexpenses',
    sa.Column('finperiodid', sa.Integer(), nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('expensedesc', sa.String(), nullable=False),
    sa.Column('budgetamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actualamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('varianceamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_oneoff', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('revision_snapshot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revision_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budgetid', 'expensedesc'], ['expenseitems.budgetid', 'expenseitems.expensedesc'], ),
    sa.ForeignKeyConstraint(['finperiodid'], ['financialperiods.finperiodid'], ),
    sa.PrimaryKeyConstraint('finperiodid', 'budgetid', 'expensedesc')
    )
    op.create_table('periodincome',
    sa.Column('finperiodid', sa.Integer(), nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('incomedesc', sa.String(), nullable=False),
    sa.Column('budgetamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actualamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('varianceamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('system_key', sa.String(), nullable=True),
    sa.Column('revision_snapshot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finperiodid'], ['financialperiods.finperiodid'], ),
    sa.PrimaryKeyConstraint('finperiodid', 'incomedesc')
    )
    op.create_table('periodinvestments',
    sa.Column('finperiodid', sa.Integer(), nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('investmentdesc', sa.String(), nullable=False),
    sa.Column('opening_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closing_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budgeted_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actualamount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revision_snapshot', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revision_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['budgetid', 'investmentdesc'], ['investmentitems.budgetid', 'investmentitems.investmentdesc'], ),
    sa.ForeignKeyConstraint(['finperiodid'], ['financialperiods.finperiodid'], ),
    sa.PrimaryKeyConstraint('finperiodid', 'investmentdesc')
    )
    op.create_table('periodtransactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finperiodid', sa.Integer(), nullable=False),
    sa.Column('budgetid', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('entrydate', sa.DateTime(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('system_reason', sa.String(), nullable=True),
    sa.Column('source_key', sa.String(), nullable=True),
    sa.Column('source_label', sa.String(), nullable=True),
    sa.Column('affected_account_desc', sa.String(), nullable=True),
    sa.Column('related_account_desc', sa.String(), nullable=True),
    sa.Column('linked_incomedesc', sa.String(), nullable=True),
    sa.Column('legacy_table', sa.String(), nullable=True),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=True),
    sa.Column('entry_kind', sa.String(), nullable=False),
    sa.Column('line_status', sa.String(), nullable=True),
    sa.Column('budget_scope', sa.String(), nullable=True),
    sa.Column('budget_before_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_after_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revisionnum', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['finperiodid'], ['financialperiods.finperiodid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_periodtransactions_dedupe'),
    sa.UniqueConstraint('legacy_table', 'legacy_id', name='uq_periodtransactions_legacy')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodtransactions')
    op.drop_table('periodinvestments')
    op.drop_table('periodincome')
    op.drop_table('periodexpenses')
    op.drop_table('periodcloseouts')
    op.drop_table('periodbalances')
    op.drop_table('setuprevisionevents')
    op.drop_table('investmentitems')
    op.drop_table('incometypes')
    op.drop_table('financialperiods')
    op.drop_table('expenseitems')
    op.drop_table('balancetypes')
    op.drop_table('paytypes')
    op.drop_table('budgets')
    # ### end Alembic commands ###
