PLANNED = "PLANNED"
ACTIVE = "ACTIVE"
CLOSED = "CLOSED"
CURRENT_STAGE = "CURRENT"
PENDING_CLOSURE_STAGE = "PENDING_CLOSURE"

CARRIED_FORWARD_DESC = "Carried Forward"
CARRIED_FORWARD_SYSTEM_KEY = "carry_forward"

WORKING = "Current"
PAID = "Paid"
REVISED = "Revised"
